apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: logging
  annotations:
    # REEMPLAZA 'ARN_DEL_ROL_OPENSEARCH_REEMPLAZAME' por tu opensearch_iam_role_arn real de los outputs de terraform
    eks.amazonaws.com/role-arn: "arn:aws:iam::038403438803:role/eks-learn-cluster-opensearch-irsa-role"
