apiVersion: v1
kind: ServiceAccount
metadata:
  # El nombre DEBE coincidir con el especificado en la relación de confianza del rol en Terraform
  name: app-s3-service-account
  namespace: app-s3
  annotations:
    # Vinculación de IRSA: Le dice a AWS EKS qué rol de IAM asociar a esta ServiceAccount.
    # REEMPLAZA EL VALOR DE ABAJO POR TU 's3_iam_role_arn' (Obtenido de terraform output)
    eks.amazonaws.com/role-arn: "arn:aws:iam::038403438803:role/eks-learn-cluster-s3-irsa-role"
