# Recurso de tipo Application para la app Azul
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  # Nombre de la aplicación en el panel de ArgoCD
  name: app-blue
  # Namespace de ArgoCD
  namespace: argocd

spec:
  project: default

  # ORIGEN: Carpeta 'kubernetes/app-blue' en tu repositorio de GitHub
  source:
    repoURL: https://github.com/BernardinoBeltran/gitops-test.git
    targetRevision: HEAD
    path: kubernetes/app-blue

  # DESTINO: Se despliega en el namespace físico 'app-blue'
  destination:
    server: https://kubernetes.default.svc
    namespace: app-blue

  # Sincronización automática activa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
